apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickchain
spec:
  selector:
    matchLabels:
      app: kickchain
  replicas: 1
  template:
    metadata:
      labels:
        app: kickchain
    spec:
      containers:
      - name: kickchain-app
        image: gcr.io/kickchain-206706/kickchain:3
        ports:
        - containerPort: 8080
        command: ["java"]
        args:
        - -Djava.security.egd=file:/dev/./urandom
        - -jar
        - /kickchain.jar
        - --spring.data.neo4j.uri=bolt://neo4j-core-0.neo4j.default.svc.cluster.local
        - --spring.data.neo4j.username=neo4j
